config/routes.rb
Rails.application.routes.draw do

	#root :to => redirect('/empresas')
	devise_for :users

	resources :empresas

	root :to => "empresas#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord

	mount_uploader :imagem, ImagemUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.paginate :page => params[:page], :per_page => 3

    @count = 1;
    @page_title = "Empresas"
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
      @empresa = Empresa.new
    @page_title = "Adicionar Empresa"
  end

  # GET /empresas/1/edit
  def edit
    @page_title = "Editar Empresa"
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa criada com sucesso!' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa excluída com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :telefone, :email, :endereco, :descricao, :imagem, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_with(model: empresa, local: true, :html => { :multipart => true }) do |form| %>
  <% if empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empresa.errors.count, "error") %> Empresa já existente:</h2>

      <ul>
      <% empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :empresa_nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :empresa_telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :empresa_email %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, id: :empresa_endereco %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :empresa_descricao %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.file_field :imagem, id: :empresa_imagem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<%= render 'form', empresa: @empresa %>
<%= link_to 'Mostrar', @empresa %> |
<%= link_to 'Voltar', empresas_path %>

app/views/empresas/index.html.erb
    <div class="conteiner">
    <div class="row">
    <% @empresas.each do |empresa| %>
      <div class="col-md-4 portfolio-item">
        <a href="#">
          <% if empresa.imagem.present? %>
          <%= image_tag(empresa.imagem, :size => '360x205')  %>
          <% else %>
          <%= image_tag("default.png", :size => '360x205')%>
          <% end %>
        </a>
        <h3>
            <a href="#"><%= empresa.nome %></a>
        </h3>
        <p><%= empresa.descricao %><br><%= link_to 'Mostrar mais |', empresa%>
          <%if current_user.try(:admin)%><%= link_to 'Editar |', edit_empresa_path(empresa) %><%end%>
          <%if current_user.try(:admin)%><%= link_to 'Excluir', empresa, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir essa empresa?' } %><%end%>
        </p>

      </div>

            <% @count+= 1 %>
            <%if @count > 3 %>
              </div>
              <div class="row">
              <% @count = 1 %>
            <% end %>

   <% end %>
   </div>
   <div class="conteiner"><%= will_paginate @empresas %></div>
</table>

app/views/empresas/new.html.erb
<%= render 'form', empresa: @empresa %>

<%= link_to 'Voltar', empresas_path %>

app/views/empresas/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Empresa
                <small><%= @empresa.nome %></small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <% if @empresa.imagem.present? %>
              <%= image_tag(@empresa.imagem_url, :size => '700x400') %>
            <%else%>
              <%= image_tag("default.png", :size => '700x400') %>
            <%end%>
        </div>

        <div class="col-md-4">
            <h3>Descrição da Empresa</h3>
            <p><%= @empresa.descricao%></p>
            <h3>Detalhes</h3>
            <ul>
                <li>Telefone: <%= @empresa.telefone%></li>
                <li>Endereço: <%= @empresa.endereco%></li>
            </ul>
        </div>
    </div><p>
</p>

<%if current_user.try(:admin) %>
  <%= link_to 'Editar', edit_empresa_path(@empresa) %> |
  <%= link_to 'Excluir', @empresa, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir essa empresa?' } %> | 
<%end%>
<%= link_to 'Voltar', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DivulgaWeb</title>
    <%= csrf_meta_tags %>

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/portfolio-item.css" rel="stylesheet">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <script src="js/jquery.js"></script>

    <script src="js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
            </div>
              <% if user_signed_in? %>
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Acessar <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Lista de Empresas', empresas_path %></li>
                    </ul>
                  </li>
                </ul>
              <% end %>
              
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gerenciar <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Nova Empresa', new_empresa_path %></li>
                    </ul>
                  </li>
                </ul>
              
              <ul class="nav navbar-nav pull-right">
                  <% if user_signed_in? %>
                    <li class="navbar-text"><%= current_user.email%></li>
                    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                  <% else %>
                    <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
                    <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                  <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
    </nav>
    <header>
      <div class="container">
        <h2><%= @page_title %></h2>
      </div>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  		<%= yield %>
    </div>
	</div>

  <footer>
      <div class="row modal-footer">
          <div class="col-lg-12">
              <p>Copyright &copy; FGA - UnB 2017</p>
          </div>
      </div>
      <!-- /.row -->
  </footer>
  </body>
</html>